### ISSUE TITLE
Upload to nextcloud not working

### ISSUE THREAD

**Issue by gutleib** [heyvaldemar/nextcloud-onlyoffice-traefik-letsencrypt-docker-compose#1]
Hi!
Thanks for great tutorial and compose template. It really does bring up an instance in a few minutes.
But I'm having issues with using it.

Few words about tweaking and usecase. I'm migrating an existing instance to one brought up by your yml, but my host is not accessible by white ip address. I have a Caddy reverse proxy that does all Letsencrypt stuss for all my web services, and it is used for Nextcloud too.

I have commented out Traefic container creation, and instead just use random ports for NC and OO on NC host VM. All traffic is proxied through Caddy, and cors and ssl are set up there.

So far so good, everything is accessible and NC and OO do successfully integrate. But now I have 2 issues:
1. Nextcloud doesn't allow me to upload anything, except small (sub-hundred kb) files.
2. When trying to "Download as" from OO, I get "Unknown error" after about a couple of minutes. Also, in message Connection lost / Connection restored do appear down on the editor page.

Does that sound familiar? Maybe you have a suggestion where could I start looking for a solution?

**Comment by heyvaldemar** [comment]
For the Nextcloud upload problem, it sounds like it could be related to PHP settings. Have you checked the `upload_max_filesize` and `post_max_size` in your PHP config? They might be set too low.

As for the "Download as" issue with OnlyOffice, it's a bit trickier. The "Connection lost / Connection restored" messages suggest there might be some network instability between Nextcloud and OnlyOffice. Since you're using Caddy as a reverse proxy, have you made sure that it's configured to handle WebSockets properly? OnlyOffice uses them for real-time collaboration, and if they're not being proxied correctly, it could cause problems.

Let's discuss this on our [Discord](https://discord.gg/AJQGCCBcqf) server; it'll be more convenient.
